### ISSUE TITLE
regarding 2 heads training

### ISSUE THREAD

**Issue by wenouyang** [EdwardTyantov/ultrasound-nerve-segmentation#1]
Hi Edward,

Thanks for sharing your code.

Would you like to help clarify some questions?
1)  What are the differences between train.py, train_generator.py and train_kfold.py?
2)  In the description, you mentioned  “2 heads training: auxiliary branch for scoring nerve presence (in the middle of the network), one branch for segmentation”? How do you instantiate? Or in which part of the code, you implement this mechanism? 

Thanks a lot.

**Comment by EdwardTyantov** [comment]
Hi,
1) train.py - classic batch train, train_generator.py - using on the fly generator (adapted image generator from keras library), kfold - same as train.py, but with k-fold cross validation.
2) there are outputs in the model (model.py), the train set is adapted : x_i : (y_1_i, y_2_i) (train.py)

**Comment by wenouyang** [comment]
Thanks.
