### ISSUE TITLE
upsampling2D and deconvolution2D

### ISSUE THREAD

**Issue by wenouyang** [EdwardTyantov/ultrasound-nerve-segmentation#10]
Hi Edward,

In this u-net implementation, there are multiple usages of "`merge`" along with "`upsampling`". For instance.  ` up6 = merge([UpSampling2D(size=(2, 2))(conv5), after_conv4], mode='concat', concat_axis=1)`

I can see that `upsampling` is to enlarge the size of layer, like `conv5`. In some paper, like Fully Convolutional Network, they use` transposed convolution`, (the corresponding Keras  implementation is `Deconvolution2D`). Does it make sense to use `Deconvolution2D` to replace `upsampling2D`? 

Thanks.

**Comment by EdwardTyantov** [comment]
Hi, wenouyang. I found it not increasing any metrics at all, basically it's pretty much the same as upsampling + conv of the same size/stride.
