### ISSUE TITLE
the range of image array after standarization and pre-processing

### ISSUE THREAD

**Issue by wenouyang** [EdwardTyantov/ultrasound-nerve-segmentation#7]
Hi Edward,

I have a question regarding the image pre-processing part.

Were you trying to scale the image array to `[0, 1]` range, or keep the image array in `[0, 255]` range? Which one will be better for training the neural network?

I checked your code, it seems that the image array is still in the range of `[0,255]` after  the function of `standartize(self, array, to_float=False)`? Is that right? Thanks.

**Comment by EdwardTyantov** [comment]
Hi, I've tried both, it didn't matter. I only rescale the target mask, function norm_mask

**Comment by wenouyang** [comment]
Thanks a lot!
